/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itsx.slasher.italikacesitmanagement.view;

/**
 *
 * @author defin
 */
public class DashboardLayout extends javax.swing.JFrame {

    /**
     * Creates new form DashboardLayout
     */
    public DashboardLayout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navbarDashboard = new javax.swing.JPanel();
        logoutLayoutButton = new javax.swing.JButton();
        typeWorkDialogButton = new javax.swing.JButton();
        vehiclesLayoutButton = new javax.swing.JButton();
        mechanicsLayoutButton = new javax.swing.JButton();
        clientLayoutButton = new javax.swing.JButton();
        serviceManagerLayoutButton = new javax.swing.JButton();
        logoItalika = new javax.swing.JLabel();
        tabbedDashboard = new javax.swing.JPanel();
        paneDashboard = new javax.swing.JTabbedPane();
        graphSpace = new javax.swing.JPanel();
        barChart = new javax.swing.JPanel();
        paiChart1 = new javax.swing.JPanel();
        paiChart2 = new javax.swing.JPanel();
        formWork = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        folioServiceField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        typeServiceCBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        mechanicCBox = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        vehicleCBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        priceServiceField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        agregarServicioButton = new javax.swing.JButton();
        folioServiceValidation = new javax.swing.JLabel();
        typeServiceWorkValidation = new javax.swing.JLabel();
        mechanicWorkValidation = new javax.swing.JLabel();
        vehicleWorkValidation = new javax.swing.JLabel();
        priceWorkValidation = new javax.swing.JLabel();
        dateReceiveWorkValidation = new javax.swing.JLabel();
        dateSendWorkValidation = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        clientCBox = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuesTPane = new javax.swing.JTextArea();
        clientWorkValidation = new javax.swing.JLabel();
        issuesWorkValidation = new javax.swing.JLabel();
        dateReceive = new com.toedter.calendar.JDateChooser();
        dateSend = new com.toedter.calendar.JDateChooser();
        formClient = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        folioClientField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nameClientField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lastNameClientField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        motherLastNameClientField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cellphoneClientField = new javax.swing.JTextField();
        agregarClienteButton = new javax.swing.JToggleButton();
        folioClientValidation = new javax.swing.JLabel();
        nameClientValidation = new javax.swing.JLabel();
        lastNameClientValidation = new javax.swing.JLabel();
        motherLastNameClientValidation = new javax.swing.JLabel();
        cellphoneClientValidation = new javax.swing.JLabel();
        formMechanic = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        folioMechanicField = new javax.swing.JTextField();
        folioMechanicValidation = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameMechanicField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lastNameMechanicField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        motherLastNameMechanicField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        specialityMechanicField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cellphoneMechanicField = new javax.swing.JTextField();
        agregarMecanicoButton = new javax.swing.JToggleButton();
        nameMechanicValidation = new javax.swing.JLabel();
        lastNameMechanicValidation = new javax.swing.JLabel();
        motherLastNameMechanicValidation = new javax.swing.JLabel();
        specialityMechanicValidation = new javax.swing.JLabel();
        cellphoneMechanicValidation = new javax.swing.JLabel();
        formVehicle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        plaqueVehicleField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        brandVehicleField = new javax.swing.JTextField();
        modelVehicleField = new javax.swing.JTextField();
        yearVehicleCBox = new javax.swing.JComboBox<>();
        agregarVehiculoButton = new javax.swing.JButton();
        plaqueVehicleValidation = new javax.swing.JLabel();
        brandVehicleValidation = new javax.swing.JLabel();
        modelVehicleValidation = new javax.swing.JLabel();
        yearVehicleValidation = new javax.swing.JLabel();
        formTypeOfWork = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        folioTWorkField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTWorkField = new javax.swing.JTextField();
        folioTWorkValidation = new javax.swing.JLabel();
        agregarTipoDeTrabajoButton = new javax.swing.JButton();
        nameTWorkValidation = new javax.swing.JLabel();

        logoutLayoutButton.setText("Cerrar sesion");
        logoutLayoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLayoutButtonActionPerformed(evt);
            }
        });

        typeWorkDialogButton.setText("T. Trabajos");

        vehiclesLayoutButton.setText("Vehiculos");

        mechanicsLayoutButton.setText("Mecanicos");

        clientLayoutButton.setText("Clientes");

        serviceManagerLayoutButton.setText("Servicios");

        logoItalika.setIcon(new javax.swing.ImageIcon("C:\\Users\\defin\\OneDrive\\Imágenes\\italika (1).png")); // NOI18N

        javax.swing.GroupLayout navbarDashboardLayout = new javax.swing.GroupLayout(navbarDashboard);
        navbarDashboard.setLayout(navbarDashboardLayout);
        navbarDashboardLayout.setHorizontalGroup(
            navbarDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbarDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoItalika, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(serviceManagerLayoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientLayoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mechanicsLayoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehiclesLayoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeWorkDialogButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutLayoutButton)
                .addContainerGap())
        );
        navbarDashboardLayout.setVerticalGroup(
            navbarDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(navbarDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeWorkDialogButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehiclesLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mechanicsLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clientLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serviceManagerLayoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(logoItalika, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        paneDashboard.setToolTipText("");
        paneDashboard.setName(""); // NOI18N

        javax.swing.GroupLayout barChartLayout = new javax.swing.GroupLayout(barChart);
        barChart.setLayout(barChartLayout);
        barChartLayout.setHorizontalGroup(
            barChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
        barChartLayout.setVerticalGroup(
            barChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paiChart1Layout = new javax.swing.GroupLayout(paiChart1);
        paiChart1.setLayout(paiChart1Layout);
        paiChart1Layout.setHorizontalGroup(
            paiChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );
        paiChart1Layout.setVerticalGroup(
            paiChart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 241, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paiChart2Layout = new javax.swing.GroupLayout(paiChart2);
        paiChart2.setLayout(paiChart2Layout);
        paiChart2Layout.setHorizontalGroup(
            paiChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paiChart2Layout.setVerticalGroup(
            paiChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 321, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graphSpaceLayout = new javax.swing.GroupLayout(graphSpace);
        graphSpace.setLayout(graphSpaceLayout);
        graphSpaceLayout.setHorizontalGroup(
            graphSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphSpaceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(graphSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paiChart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paiChart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        graphSpaceLayout.setVerticalGroup(
            graphSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphSpaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(graphSpaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(barChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(graphSpaceLayout.createSequentialGroup()
                        .addComponent(paiChart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(paiChart2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        paneDashboard.addTab("Administracion", graphSpace);

        jLabel18.setText("Folio");

        folioServiceField.setEnabled(false);

        jLabel19.setText("Tipo de servicio");

        typeServiceCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel20.setText("Mecanico encargado");

        mechanicCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel21.setText("Vehiculo a reparar");

        vehicleCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel22.setText("Costo de servicio");

        jLabel23.setText("Fecha y hora de recibido (vehiculo)");

        jLabel24.setText("Fecha y hora de entrega (vehiculo)");

        agregarServicioButton.setText("Registrar");

        folioServiceValidation.setText("Se genera automaticamente");

        jLabel25.setText("Folio de cliente");

        clientCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel26.setText("Fallas");

        issuesTPane.setColumns(20);
        issuesTPane.setRows(5);
        jScrollPane1.setViewportView(issuesTPane);

        dateReceive.setDateFormatString("yyyy/MM/dd HH:mm.ss");

        dateSend.setDateFormatString("yyyy/MM/dd HH:mm.ss");

        javax.swing.GroupLayout formWorkLayout = new javax.swing.GroupLayout(formWork);
        formWork.setLayout(formWorkLayout);
        formWorkLayout.setHorizontalGroup(
            formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formWorkLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarServicioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formWorkLayout.createSequentialGroup()
                        .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel20)
                                .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel25)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folioServiceField)
                            .addComponent(typeServiceCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mechanicCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(priceServiceField)
                            .addComponent(vehicleCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                            .addComponent(dateReceive, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(formWorkLayout.createSequentialGroup()
                                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(issuesWorkValidation)
                                    .addComponent(clientWorkValidation)
                                    .addComponent(dateSendWorkValidation)
                                    .addComponent(dateReceiveWorkValidation)
                                    .addComponent(priceWorkValidation)
                                    .addComponent(vehicleWorkValidation)
                                    .addComponent(mechanicWorkValidation)
                                    .addComponent(typeServiceWorkValidation)
                                    .addComponent(folioServiceValidation))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(dateSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(119, 119, 119))
        );
        formWorkLayout.setVerticalGroup(
            formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formWorkLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(folioServiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(folioServiceValidation)
                .addGap(10, 10, 10)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(typeServiceCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(typeServiceWorkValidation)
                .addGap(12, 12, 12)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(mechanicCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mechanicWorkValidation)
                .addGap(12, 12, 12)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(vehicleCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vehicleWorkValidation)
                .addGap(18, 18, 18)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(priceServiceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(priceWorkValidation)
                .addGap(11, 11, 11)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23)
                    .addComponent(dateReceive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateReceiveWorkValidation)
                .addGap(18, 18, 18)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(dateSend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateSendWorkValidation)
                .addGap(17, 17, 17)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addComponent(clientCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(clientWorkValidation)
                .addGroup(formWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formWorkLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formWorkLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(issuesWorkValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(agregarServicioButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneDashboard.addTab("Nuevo servicio", formWork);

        jLabel8.setText("Folio");

        folioClientField.setEnabled(false);

        jLabel14.setText("Nombre");

        jLabel15.setText("Apellido paterno");

        jLabel16.setText("Apellido materno");

        motherLastNameClientField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motherLastNameClientFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("Numero de telefono");

        agregarClienteButton.setText("Registrar");

        folioClientValidation.setText("Se genera automaticamente");

        javax.swing.GroupLayout formClientLayout = new javax.swing.GroupLayout(formClient);
        formClient.setLayout(formClientLayout);
        formClientLayout.setHorizontalGroup(
            formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formClientLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarClienteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formClientLayout.createSequentialGroup()
                        .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folioClientValidation)
                            .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(folioClientField)
                                .addComponent(nameClientField, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                .addComponent(lastNameClientField)
                                .addComponent(motherLastNameClientField)
                                .addComponent(cellphoneClientField))
                            .addComponent(nameClientValidation)
                            .addComponent(lastNameClientValidation)
                            .addComponent(motherLastNameClientValidation)
                            .addComponent(cellphoneClientValidation))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        formClientLayout.setVerticalGroup(
            formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formClientLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(folioClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(folioClientValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nameClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameClientValidation)
                .addGap(9, 9, 9)
                .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lastNameClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameClientValidation)
                .addGap(9, 9, 9)
                .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(motherLastNameClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motherLastNameClientValidation)
                .addGap(9, 9, 9)
                .addGroup(formClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cellphoneClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneClientValidation)
                .addGap(29, 29, 29)
                .addComponent(agregarClienteButton)
                .addContainerGap(288, Short.MAX_VALUE))
        );

        paneDashboard.addTab("Agregar cliente", formClient);

        jLabel7.setText("Folio");

        folioMechanicField.setEnabled(false);

        folioMechanicValidation.setText("Se genera automaticamente");

        jLabel9.setText("Nombre");

        nameMechanicField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameMechanicFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Apellido paterno");

        jLabel11.setText("Apellido materno");

        jLabel12.setText("Especialidad");

        jLabel13.setText("Numero de telefono");

        agregarMecanicoButton.setText("Registrar");

        javax.swing.GroupLayout formMechanicLayout = new javax.swing.GroupLayout(formMechanic);
        formMechanic.setLayout(formMechanicLayout);
        formMechanicLayout.setHorizontalGroup(
            formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formMechanicLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarMecanicoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(formMechanicLayout.createSequentialGroup()
                        .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameMechanicField)
                            .addComponent(motherLastNameMechanicField)
                            .addComponent(specialityMechanicField)
                            .addComponent(cellphoneMechanicField)
                            .addComponent(nameMechanicField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(formMechanicLayout.createSequentialGroup()
                                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cellphoneMechanicValidation)
                                    .addComponent(specialityMechanicValidation)
                                    .addComponent(motherLastNameMechanicValidation)
                                    .addComponent(lastNameMechanicValidation)
                                    .addComponent(folioMechanicValidation)
                                    .addComponent(nameMechanicValidation))
                                .addGap(0, 147, Short.MAX_VALUE))
                            .addComponent(folioMechanicField, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(158, 158, 158))
        );
        formMechanicLayout.setVerticalGroup(
            formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formMechanicLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(folioMechanicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(folioMechanicValidation)
                .addGap(30, 30, 30)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(nameMechanicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameMechanicValidation)
                .addGap(21, 21, 21)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lastNameMechanicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastNameMechanicValidation)
                .addGap(19, 19, 19)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(motherLastNameMechanicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motherLastNameMechanicValidation)
                .addGap(13, 13, 13)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(specialityMechanicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialityMechanicValidation)
                .addGap(14, 14, 14)
                .addGroup(formMechanicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cellphoneMechanicField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneMechanicValidation)
                .addGap(18, 18, 18)
                .addComponent(agregarMecanicoButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        paneDashboard.addTab("Agregar mecanico", formMechanic);

        jLabel3.setText("Placa");

        jLabel4.setText("Marca");

        jLabel5.setText("Modelo");

        jLabel6.setText("Año");

        yearVehicleCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));

        agregarVehiculoButton.setText("Registrar");
        agregarVehiculoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarVehiculoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formVehicleLayout = new javax.swing.GroupLayout(formVehicle);
        formVehicle.setLayout(formVehicleLayout);
        formVehicleLayout.setHorizontalGroup(
            formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formVehicleLayout.createSequentialGroup()
                .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(agregarVehiculoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formVehicleLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yearVehicleValidation)
                            .addComponent(yearVehicleCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formVehicleLayout.createSequentialGroup()
                            .addGap(177, 177, 177)
                            .addComponent(jLabel3)
                            .addGap(18, 18, 18)
                            .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(plaqueVehicleValidation)
                                .addComponent(plaqueVehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(formVehicleLayout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(brandVehicleValidation)
                                .addComponent(brandVehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(formVehicleLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelVehicleValidation)
                            .addComponent(modelVehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        formVehicleLayout.setVerticalGroup(
            formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formVehicleLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(plaqueVehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(plaqueVehicleValidation)
                .addGap(9, 9, 9)
                .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(brandVehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brandVehicleValidation)
                .addGap(8, 8, 8)
                .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(modelVehicleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(modelVehicleValidation)
                .addGap(18, 18, 18)
                .addGroup(formVehicleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yearVehicleCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearVehicleValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(agregarVehiculoButton)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        paneDashboard.addTab("Agregar vehiculo", formVehicle);

        jLabel1.setText("Folio");

        folioTWorkField.setEnabled(false);

        jLabel2.setText("Nombre del trabajo");

        nameTWorkField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTWorkFieldActionPerformed(evt);
            }
        });

        folioTWorkValidation.setText("Se genera automaticamente");

        agregarTipoDeTrabajoButton.setText("Registrar");

        javax.swing.GroupLayout formTypeOfWorkLayout = new javax.swing.GroupLayout(formTypeOfWork);
        formTypeOfWork.setLayout(formTypeOfWorkLayout);
        formTypeOfWorkLayout.setHorizontalGroup(
            formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTypeOfWorkLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formTypeOfWorkLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folioTWorkValidation)
                            .addComponent(folioTWorkField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(agregarTipoDeTrabajoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(formTypeOfWorkLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTWorkValidation)
                            .addComponent(nameTWorkField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        formTypeOfWorkLayout.setVerticalGroup(
            formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formTypeOfWorkLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(folioTWorkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(folioTWorkValidation)
                .addGap(21, 21, 21)
                .addGroup(formTypeOfWorkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameTWorkField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameTWorkValidation)
                .addGap(18, 18, 18)
                .addComponent(agregarTipoDeTrabajoButton)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        paneDashboard.addTab("Agregar tipo de trabajo", formTypeOfWork);

        javax.swing.GroupLayout tabbedDashboardLayout = new javax.swing.GroupLayout(tabbedDashboard);
        tabbedDashboard.setLayout(tabbedDashboardLayout);
        tabbedDashboardLayout.setHorizontalGroup(
            tabbedDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabbedDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneDashboard)
                .addContainerGap())
        );
        tabbedDashboardLayout.setVerticalGroup(
            tabbedDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabbedDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneDashboard)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navbarDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navbarDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbedDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLayoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLayoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutLayoutButtonActionPerformed

    private void nameTWorkFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTWorkFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTWorkFieldActionPerformed

    private void agregarVehiculoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarVehiculoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarVehiculoButtonActionPerformed

    private void nameMechanicFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameMechanicFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameMechanicFieldActionPerformed

    private void motherLastNameClientFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motherLastNameClientFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motherLastNameClientFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton agregarClienteButton;
    public javax.swing.JToggleButton agregarMecanicoButton;
    public javax.swing.JButton agregarServicioButton;
    public javax.swing.JButton agregarTipoDeTrabajoButton;
    public javax.swing.JButton agregarVehiculoButton;
    public javax.swing.JPanel barChart;
    public javax.swing.JTextField brandVehicleField;
    public javax.swing.JLabel brandVehicleValidation;
    public javax.swing.JTextField cellphoneClientField;
    public javax.swing.JLabel cellphoneClientValidation;
    public javax.swing.JTextField cellphoneMechanicField;
    public javax.swing.JLabel cellphoneMechanicValidation;
    public javax.swing.JComboBox<String> clientCBox;
    public javax.swing.JButton clientLayoutButton;
    public javax.swing.JLabel clientWorkValidation;
    public com.toedter.calendar.JDateChooser dateReceive;
    public javax.swing.JLabel dateReceiveWorkValidation;
    public com.toedter.calendar.JDateChooser dateSend;
    public javax.swing.JLabel dateSendWorkValidation;
    public javax.swing.JTextField folioClientField;
    public javax.swing.JLabel folioClientValidation;
    public javax.swing.JTextField folioMechanicField;
    public javax.swing.JLabel folioMechanicValidation;
    public javax.swing.JTextField folioServiceField;
    public javax.swing.JLabel folioServiceValidation;
    public javax.swing.JTextField folioTWorkField;
    public javax.swing.JLabel folioTWorkValidation;
    private javax.swing.JPanel formClient;
    private javax.swing.JPanel formMechanic;
    private javax.swing.JPanel formTypeOfWork;
    private javax.swing.JPanel formVehicle;
    private javax.swing.JPanel formWork;
    private javax.swing.JPanel graphSpace;
    public javax.swing.JTextArea issuesTPane;
    public javax.swing.JLabel issuesWorkValidation;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField lastNameClientField;
    public javax.swing.JLabel lastNameClientValidation;
    public javax.swing.JTextField lastNameMechanicField;
    public javax.swing.JLabel lastNameMechanicValidation;
    private javax.swing.JLabel logoItalika;
    public javax.swing.JButton logoutLayoutButton;
    public javax.swing.JComboBox<String> mechanicCBox;
    public javax.swing.JLabel mechanicWorkValidation;
    public javax.swing.JButton mechanicsLayoutButton;
    public javax.swing.JTextField modelVehicleField;
    public javax.swing.JLabel modelVehicleValidation;
    public javax.swing.JTextField motherLastNameClientField;
    public javax.swing.JLabel motherLastNameClientValidation;
    public javax.swing.JTextField motherLastNameMechanicField;
    public javax.swing.JLabel motherLastNameMechanicValidation;
    public javax.swing.JTextField nameClientField;
    public javax.swing.JLabel nameClientValidation;
    public javax.swing.JTextField nameMechanicField;
    public javax.swing.JLabel nameMechanicValidation;
    public javax.swing.JTextField nameTWorkField;
    public javax.swing.JLabel nameTWorkValidation;
    private javax.swing.JPanel navbarDashboard;
    public javax.swing.JPanel paiChart1;
    public javax.swing.JPanel paiChart2;
    private javax.swing.JTabbedPane paneDashboard;
    public javax.swing.JTextField plaqueVehicleField;
    public javax.swing.JLabel plaqueVehicleValidation;
    public javax.swing.JTextField priceServiceField;
    public javax.swing.JLabel priceWorkValidation;
    public javax.swing.JButton serviceManagerLayoutButton;
    public javax.swing.JTextField specialityMechanicField;
    public javax.swing.JLabel specialityMechanicValidation;
    private javax.swing.JPanel tabbedDashboard;
    public javax.swing.JComboBox<String> typeServiceCBox;
    public javax.swing.JLabel typeServiceWorkValidation;
    public javax.swing.JButton typeWorkDialogButton;
    public javax.swing.JComboBox<String> vehicleCBox;
    public javax.swing.JLabel vehicleWorkValidation;
    public javax.swing.JButton vehiclesLayoutButton;
    public javax.swing.JComboBox<String> yearVehicleCBox;
    public javax.swing.JLabel yearVehicleValidation;
    // End of variables declaration//GEN-END:variables
}
