/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itsx.slasher.italikacesitmanagement.view;

import com.itsx.slasher.italikacesitmanagement.model.Mechanic;
import com.itsx.slasher.italikacesitmanagement.service.MechanicService;

/**
 *
 * @author defin
 */
public class MechanicDialog extends javax.swing.JFrame {

    private MechanicService mechanicService;

    /**
     * Creates new form MechanicDialog
     */
    public MechanicDialog(MechanicService mechanicService) {
        initComponents();
        setTitle("Mecanico");
        setResizable(true);
        setLocationRelativeTo(null);

        this.mechanicService = mechanicService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        deleteMechanicDialogButton = new javax.swing.JButton();
        updateMechanicDialogButton = new javax.swing.JButton();
        cellphoneMechanicDialogValidation = new javax.swing.JLabel();
        cellphoneMechanicDialogField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        specialityMechanicDialogValidation = new javax.swing.JLabel();
        specialityMechanicDialogField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        motherLastnameMechanicDialogValidation = new javax.swing.JLabel();
        motherLastnameMechanicDialogField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lastnameMechanicDialogValidation = new javax.swing.JLabel();
        lastnameMechanicDialogField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameMechanicDialogValidation = new javax.swing.JLabel();
        nameMechanicDialogField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        folioMechanicDialogField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        mechanicTitleDialog = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableMechanicDialog = new javax.swing.JTable();

        deleteMechanicDialogButton.setText("Eliminar");

        updateMechanicDialogButton.setText("Actualizar");

        jLabel6.setText("Numero de telefono");

        jLabel5.setText("Especialidad");

        jLabel4.setText("Apellido materno");

        jLabel3.setText("Apellido paterno");

        jLabel2.setText("Nombre");

        folioMechanicDialogField.setEnabled(false);

        jLabel1.setText("Folio");

        mechanicTitleDialog.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mechanicTitleDialog.setText("Mecanico");

        tableMechanicDialog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Nombre", "Apellido paterno", "Apellido materno", "Especialidad", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMechanicDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMechanicDialogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableMechanicDialog);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(updateMechanicDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mechanicTitleDialog)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(deleteMechanicDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(folioMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameMechanicDialogValidation)
                                    .addComponent(lastnameMechanicDialogValidation)
                                    .addComponent(motherLastnameMechanicDialogValidation)
                                    .addComponent(specialityMechanicDialogValidation)
                                    .addComponent(cellphoneMechanicDialogValidation)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameMechanicDialogField)
                                        .addComponent(lastnameMechanicDialogField)
                                        .addComponent(motherLastnameMechanicDialogField)
                                        .addComponent(specialityMechanicDialogField)
                                        .addComponent(cellphoneMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mechanicTitleDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folioMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameMechanicDialogValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastnameMechanicDialogValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motherLastnameMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(motherLastnameMechanicDialogValidation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(specialityMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(specialityMechanicDialogValidation)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cellphoneMechanicDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellphoneMechanicDialogValidation)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateMechanicDialogButton)
                    .addComponent(deleteMechanicDialogButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableMechanicDialogMouseClicked(java.awt.event.MouseEvent evt) {

        int row = tableMechanicDialog.getSelectedRow();
        Long selectedFolio = Long.parseLong(tableMechanicDialog.getValueAt(row, 0).toString());

        Mechanic mechanic = mechanicService.getMechanicByFolio(selectedFolio);

        folioMechanicDialogField.setText(mechanic.getFolio().toString());
        nameMechanicDialogField.setText(mechanic.getName());
        lastnameMechanicDialogField.setText(mechanic.getLastName());
        motherLastnameMechanicDialogField.setText(mechanic.getMotherLastName());
        specialityMechanicDialogField.setText(mechanic.getSpeciality());
        cellphoneMechanicDialogField.setText(mechanic.getCellphone());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MechanicDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MechanicDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MechanicDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MechanicDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MechanicDialog().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField cellphoneMechanicDialogField;
    public javax.swing.JLabel cellphoneMechanicDialogValidation;
    public javax.swing.JButton deleteMechanicDialogButton;
    public javax.swing.JTextField folioMechanicDialogField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField lastnameMechanicDialogField;
    public javax.swing.JLabel lastnameMechanicDialogValidation;
    public javax.swing.JLabel mechanicTitleDialog;
    public javax.swing.JTextField motherLastnameMechanicDialogField;
    public javax.swing.JLabel motherLastnameMechanicDialogValidation;
    public javax.swing.JTextField nameMechanicDialogField;
    public javax.swing.JLabel nameMechanicDialogValidation;
    public javax.swing.JTextField specialityMechanicDialogField;
    public javax.swing.JLabel specialityMechanicDialogValidation;
    public javax.swing.JTable tableMechanicDialog;
    public javax.swing.JButton updateMechanicDialogButton;
    // End of variables declaration//GEN-END:variables
}
