/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.itsx.slasher.italikacesitmanagement.view;

import com.itsx.slasher.italikacesitmanagement.model.Work;
import com.itsx.slasher.italikacesitmanagement.service.WorkService;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author defin
 */
public class WorkDialog extends javax.swing.JDialog {

    private WorkService workService;

    /**
     * Creates new form WorkDialog
     */
    public WorkDialog(WorkService workService, Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        setTitle("Servicios/trabajos");
        setResizable(true);
        setLocationRelativeTo(null);

        this.workService = workService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        folioWorkDialogField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typeOfWorkDialogCBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        mechanicWorkDialogCBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        vehicleWorkDialogCBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        priceWorkDialogField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        clientWorkDialogCBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        dateReceiveWorkDialogDChooser = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        dateSendWorkDialogDChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        issuesWorkDialogTArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        updateWorkDialogButton = new javax.swing.JButton();
        deleteWorkDialogButton = new javax.swing.JButton();
        folioWorkDialogValidation = new javax.swing.JLabel();
        mechanicWorkDialogValidation = new javax.swing.JLabel();
        vehicleWorkDialogValidation = new javax.swing.JLabel();
        priceWorkDialogValidation = new javax.swing.JLabel();
        clientWorkDialogValidation = new javax.swing.JLabel();
        dateReceibeWorkDialogValidation = new javax.swing.JLabel();
        dateSendWorkDialogValidation = new javax.swing.JLabel();
        issuesWorkDialogValidation = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableWorkDialog = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Trabajos/Servicios");

        jLabel2.setText("Folio");

        folioWorkDialogField.setEnabled(false);

        jLabel3.setText("Tipo de servicio");

        typeOfWorkDialogCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel4.setText("Mecanico encargado");

        mechanicWorkDialogCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel5.setText("Vehiculo a reparar");

        vehicleWorkDialogCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel6.setText("Costo de servicio");

        jLabel7.setText("Folio de cliente");

        clientWorkDialogCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel8.setText("Fecha y hora de recibido (vehiculo)");

        dateReceiveWorkDialogDChooser.setDateFormatString("yyyy/MM/dd HH:mm.ss");

        jLabel9.setText("Fecha y hora de entrega (vehiculo)");

        dateSendWorkDialogDChooser.setDateFormatString("yyyy/MM/dd HH:mm.ss");

        issuesWorkDialogTArea.setColumns(20);
        issuesWorkDialogTArea.setRows(5);
        jScrollPane1.setViewportView(issuesWorkDialogTArea);

        jLabel10.setText("Fallas");

        updateWorkDialogButton.setText("Actualizar");

        deleteWorkDialogButton.setText("Eliminar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(clientWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceWorkDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicleWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(folioWorkDialogValidation)
                            .addComponent(typeOfWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleWorkDialogValidation)
                            .addComponent(priceWorkDialogValidation)
                            .addComponent(folioWorkDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(clientWorkDialogValidation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mechanicWorkDialogValidation)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(mechanicWorkDialogCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(33, 33, 33)))
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(deleteWorkDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateWorkDialogButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateReceiveWorkDialogDChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateSendWorkDialogDChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateReceibeWorkDialogValidation)
                    .addComponent(dateSendWorkDialogValidation)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuesWorkDialogValidation))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateReceiveWorkDialogDChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(folioWorkDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(typeOfWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(folioWorkDialogValidation))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(dateReceibeWorkDialogValidation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(dateSendWorkDialogDChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateSendWorkDialogValidation)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mechanicWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mechanicWorkDialogValidation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicleWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vehicleWorkDialogValidation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceWorkDialogField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addGap(14, 14, 14)
                        .addComponent(priceWorkDialogValidation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clientWorkDialogCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clientWorkDialogValidation)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(deleteWorkDialogButton)
                                .addComponent(updateWorkDialogButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issuesWorkDialogValidation)
                        .addGap(0, 6, Short.MAX_VALUE))))
        );

        tableWorkDialog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Tipo de servicio", "Mecanico encargado", "Vehiculo a reparar", "Costo", "Folio cliente", "Fecha recibido", "Fecha entregado", "Fallas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableWorkDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableWorkDialogMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableWorkDialog);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este metodo segun la fila seleccionada de la tabla de trabajos/servicios
     * en el formulario de trabajos, se filtra el servicio seleccionado y los
     * atributos de esa fila se mandan a los campos disponibles del formulario.
     *
     * @param evt
     */
    private void tableWorkDialogMouseClicked(java.awt.event.MouseEvent evt) {

        int row = tableWorkDialog.getSelectedRow();
        Long selectedFolio = Long.parseLong(tableWorkDialog.getValueAt(row, 0).toString());

        Work selectedWork = workService.getWorkByFolio(selectedFolio);

        folioWorkDialogField.setText(selectedWork.getFolio().toString());
        typeOfWorkDialogCBox.setSelectedIndex(selectedIndex(selectedWork.getTypeOfWork().getFolio(), typeOfWorkDialogCBox));
        mechanicWorkDialogCBox.setSelectedIndex(selectedIndex(selectedWork.getMechanic().getFolio(), mechanicWorkDialogCBox));
        clientWorkDialogCBox.setSelectedIndex(selectedIndex(selectedWork.getClient().getFolio(), clientWorkDialogCBox));
        vehicleWorkDialogCBox.setSelectedIndex(selectedIndex(selectedWork.getVehicle().getPlaque()));
        priceWorkDialogField.setText(selectedWork.getCost().toString());
        dateReceiveWorkDialogDChooser.setDate(selectedWork.getFechaRecibido());
        dateSendWorkDialogDChooser.setDate(selectedWork.getFechaEntrega());
        issuesWorkDialogTArea.setText(selectedWork.getIssues());
    }

    /**
     * Este metodo retorna el indice seleccionado en el comboBox,
     * se compara el folio seleccionado con el folio del combobox.
     *
     * @param folio
     * @param comboBox
     * @return
     */
    private int selectedIndex(Long folio, JComboBox<String> comboBox) {

        int selectedIndex = 0;

        for (int index = 1; index < comboBox.getItemCount(); index++) {
            if ( folio == Long.parseLong(comboBox.getItemAt(index)) ) {
                selectedIndex = index;
                break;
            }
        }

        return selectedIndex;
    }

    /**
     * Este metodo retorna el indice seleccionado en el comboBox,
     * se compara el folio seleccionado con el folio del combobox.
     *
     * @param plaque
     * @return
     */
    private int selectedIndex(String plaque) {

        int selectedIndex = 0;

        for (int index = 0; index < typeOfWorkDialogCBox.getItemCount(); index++) {
            if ( plaque.equals(vehicleWorkDialogCBox.getItemAt(index)) ) {
                selectedIndex = index;
                break;
            }
        }

        return selectedIndex;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WorkDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WorkDialog().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> clientWorkDialogCBox;
    public javax.swing.JLabel clientWorkDialogValidation;
    public javax.swing.JLabel dateReceibeWorkDialogValidation;
    public com.toedter.calendar.JDateChooser dateReceiveWorkDialogDChooser;
    public com.toedter.calendar.JDateChooser dateSendWorkDialogDChooser;
    public javax.swing.JLabel dateSendWorkDialogValidation;
    public javax.swing.JButton deleteWorkDialogButton;
    public javax.swing.JTextField folioWorkDialogField;
    public javax.swing.JLabel folioWorkDialogValidation;
    public javax.swing.JTextArea issuesWorkDialogTArea;
    public javax.swing.JLabel issuesWorkDialogValidation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> mechanicWorkDialogCBox;
    public javax.swing.JLabel mechanicWorkDialogValidation;
    public javax.swing.JTextField priceWorkDialogField;
    public javax.swing.JLabel priceWorkDialogValidation;
    public javax.swing.JTable tableWorkDialog;
    public javax.swing.JComboBox<String> typeOfWorkDialogCBox;
    public javax.swing.JButton updateWorkDialogButton;
    public javax.swing.JComboBox<String> vehicleWorkDialogCBox;
    public javax.swing.JLabel vehicleWorkDialogValidation;
    // End of variables declaration//GEN-END:variables
}
